include $(ESHELL)Graphics_Systems/OpenGL/Makefile
include $(ESHELL)Graphics_Systems/OpenGL2-OpenGLES2/Makefile
SOURCES += $(wildcard $(ESHELL)Graphics_Systems/OpenGL2/*.cpp)

SHADER_VERSION := $(ESHELL)Graphics_Systems/OpenGL2/version.glsl
