include $(ESHELL)Graphics_Systems/OpenGL/Makefile
include $(ESHELL)Graphics_Systems/OpenGL3-OpenGLES3/Makefile
SOURCES += $(wildcard $(ESHELL)Graphics_Systems/OpenGL3/*.cpp)

SHADER_VERSION := $(ESHELL)Graphics_Systems/OpenGL3/version.glsl
